# https://hub.docker.com/_/node
image: "node:8.16.0-alpine"

cache:
  paths:
    - node_modules/

before_script:
  #- npm install -g typescript vscode
  - npm install
  #- node ./node_modules/vscode/bin/install
  - ls

test:
  script:
    - npm run compile:dev