# https://hub.docker.com/_/node
image: "node:8.16.0-jessie-slim"

cache:
  paths:
    - node_modules/

before_script:
  - apt-get install node-typescript -y
  - npm install
  - ls

test:
  script:
    - tsc -p ./
    - node ./node_modules/vscode/bin/test